#!/bin/bash  

# Prints size of payload in Byte  
# 
# Used for figuring out if i need a cache in my application.
#
# Needed dependencies:
# 1. curl
#
# Example:  
# $ curlsize "https://www.nrk.no"

curl -so /dev/null $1 -w '%{size_download}'

