#!/bin/bash

sudo apt-get clean;
sudo apt-get autoclean;
sudo apt update -y; 
sudo apt upgrade -y;
sudo apt dist-upgrade -y;
sudo apt autoremove -y;
sudo snap refresh; 
pip install --upgrade pip; 
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U;
